import { FormEvent, useEffect, useMemo, useState } from 'react'
import { BellPlus, ExternalLink, Filter, Pencil, Plus, Search, Star, Trash2 } from 'lucide-react'
import { api, euro } from '../lib/api'
import type { Category, Offer, Product, Supplier } from '../lib/types'
import { buildParameterSchema, emptyParameter, type ParameterDraft } from '../lib/parameters'
import { Badge, Button, Empty, Field, Modal } from '../components/ui'
import { useApp } from '../App'

const emptyProduct:Partial<Product>={sku:'',name:'',description:'',unit:'Stk.',manufacturer:'',model:'',parameters:{},active:true,reorderPoint:0,targetStock:0}
const emptyOffer:Partial<Offer>={supplierId:0,supplierSku:'',priceCents:0,currency:'EUR',minimumQuantity:1,packSize:1,leadDays:0,purchaseUrl:'',active:true}

export default function CatalogPage(){
 const {user,refreshKey,refresh,notify}=useApp(),[products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[q,setQ]=useState(''),[categoryId,setCategoryId]=useState(''),[preferred,setPreferred]=useState(false),[params,setParams]=useState<Record<string,string>>({}),[showFilters,setShowFilters]=useState(false),[edit,setEdit]=useState<Partial<Product>|null>(null),[detail,setDetail]=useState<Product|null>(null),[offerFor,setOfferFor]=useState<Product|null>(null),[alertFor,setAlertFor]=useState<Product|null>(null),[categoryModal,setCategoryModal]=useState(false)
 const selectedCategory=categories.find(c=>String(c.id)===categoryId)
 const load=()=>{const query=new URLSearchParams();if(q)query.set('q',q);if(categoryId)query.set('categoryId',categoryId);if(preferred)query.set('preferred','true');Object.entries(params).filter(([,v])=>v!=='').forEach(([k,v])=>query.append('param',`${k}:${v}`));api<Product[]>(`/products?${query}`).then(setProducts)}
 useEffect(()=>{Promise.all([api<Category[]>('/categories'),api<Supplier[]>('/suppliers?active=true')]).then(([c,s])=>{setCategories(c);setSuppliers(s)});load()},[refreshKey])
 useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[q,categoryId,preferred,params])
 const openDetail=async(id:number)=>setDetail(await api<Product>(`/products/${id}`))
 const remove=async(id:number)=>{if(!confirm('Artikel wirklich löschen?'))return;await api(`/products/${id}`,{method:'DELETE'});notify('Artikel gelöscht');refresh()}
 return <div className="content"><div className="page-header"><div><p className="eyebrow">Guided Buying</p><h2>Beschaffungskatalog</h2><p>Technische Parameter durchsuchen, Bezugsquellen vergleichen und direkt einkaufen.</p></div>{user.isAdmin&&<div style={{display:'flex',gap:'.5rem'}}><Button variant="ghost" onClick={()=>setCategoryModal(true)}>Kategorien</Button><Button variant="primary" onClick={()=>setEdit({...emptyProduct})}><Plus size={17}/> Artikel</Button></div>}</div>
 <div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="SKU, Artikel, Hersteller …"/></div><select value={categoryId} onChange={e=>{setCategoryId(e.target.value);setParams({})}}><option value="">Alle Kategorien</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><label className="check"><input type="checkbox" checked={preferred} onChange={e=>setPreferred(e.target.checked)}/><Star size={15}/> Preferred</label><Button variant="ghost" onClick={()=>setShowFilters(!showFilters)}><Filter size={16}/> Parameter</Button></div>
 {showFilters&&<div className="filter-grid">{selectedCategory?.parameterSchema?.length?selectedCategory.parameterSchema.map(def=><Field key={def.key} label={`${def.label}${def.unit?` (${def.unit})`:''}`}>{def.type==='select'?<select value={params[def.key]||''} onChange={e=>setParams(p=>({...p,[def.key]:e.target.value}))}><option value="">Alle</option>{def.options?.map(o=><option key={o}>{o}</option>)}</select>:def.type==='boolean'?<select value={params[def.key]||''} onChange={e=>setParams(p=>({...p,[def.key]:e.target.value}))}><option value="">Alle</option><option value="true">Ja</option><option value="false">Nein</option></select>:<input type={def.type==='number'?'number':'text'} value={params[def.key]||''} onChange={e=>setParams(p=>({...p,[def.key]:e.target.value}))}/>}</Field>):<div style={{color:'var(--text-muted)',fontSize:'.78rem'}}>Wähle eine Kategorie mit Parameterschema.</div>}</div>}
 {products.length?<div className="cards">{products.map(product=>{const offers=[...(product.offers||[])].sort((a,b)=>a.priceCents-b.priceCents),best=offers[0];return <article className="product-card" key={product.id}><div className="product-top"><Badge>{product.sku}</Badge>{best?.supplier?.preferred&&<Badge tone="pink"><Star size={11}/> Preferred</Badge>}</div><h3>{product.name}</h3><p>{product.manufacturer}{product.model&&` · ${product.model}`}</p><div className="param-chips">{Object.entries(product.parameters||{}).slice(0,5).map(([k,v])=><span className="param-chip" key={k}>{k}: {String(v)}</span>)}</div><div className="product-bottom"><div className="price"><small>{offers.length} Bezugsquelle{offers.length===1?'':'n'}</small>{best?euro(best.priceCents):'Kein Preis'}</div><div className="row-actions"><Button className="icon" variant="ghost" onClick={()=>setAlertFor(product)} title="Tiefpreis-Alarm"><BellPlus size={16}/></Button>{user.isAdmin&&<Button className="icon" variant="ghost" onClick={()=>setOfferFor(product)} title="Angebot"><Plus size={16}/></Button>}<Button variant="primary" onClick={()=>openDetail(product.id)}>Details</Button></div></div></article>})}</div>:<Empty>Keine Artikel passen zu den gewählten Parametern.</Empty>}
 {edit&&<ProductModal value={edit} categories={categories} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);notify('Artikel gespeichert');refresh()}}/>}
 {detail&&<Modal title={detail.name} wide onClose={()=>setDetail(null)} footer={<><Button variant="ghost" onClick={()=>setDetail(null)}>Schließen</Button>{user.isAdmin&&<><Button variant="danger" onClick={()=>{remove(detail.id);setDetail(null)}}><Trash2 size={16}/> Löschen</Button><Button variant="primary" onClick={()=>{setEdit(detail);setDetail(null)}}><Pencil size={16}/> Bearbeiten</Button></>}</>}><div className="form-grid"><Field label="SKU"><div className="cell-title">{detail.sku}</div></Field><Field label="Kategorie"><div>{detail.category?.name||'–'}</div></Field><Field label="Beschreibung" full><div>{detail.description||'–'}</div></Field></div><h4>Bezugsquellen</h4><div className="table-wrap"><table><thead><tr><th>Lieferant</th><th>Preis</th><th>Lieferzeit</th><th></th></tr></thead><tbody>{detail.offers?.map(o=><tr key={o.id}><td><span className="cell-title">{o.supplier?.name}</span>{o.supplier?.preferred&&<span> ★</span>}</td><td>{euro(o.priceCents)}</td><td>{o.leadDays} Tage</td><td>{o.purchaseUrl&&<a className="btn primary" href={o.purchaseUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Einkaufen</a>}</td></tr>)}</tbody></table></div></Modal>}
 {offerFor&&<OfferModal product={offerFor} suppliers={suppliers} onClose={()=>setOfferFor(null)} onSaved={()=>{setOfferFor(null);notify('Bezugsquelle gespeichert');refresh()}}/>}
 {alertFor&&<AlertModal product={alertFor} onClose={()=>setAlertFor(null)} onSaved={()=>{setAlertFor(null);notify('Tiefpreis-Alarm angelegt');refresh()}}/>}
 {categoryModal&&<CategoryModal categories={categories} onClose={()=>setCategoryModal(false)} onSaved={()=>{setCategoryModal(false);notify('Kategorie gespeichert');refresh()}}/>}
 </div>
}

function ProductModal({value,categories,onClose,onSaved}:{value:Partial<Product>;categories:Category[];onClose:()=>void;onSaved:()=>void}){
 const [form,setForm]=useState<Partial<Product>>({...value,parameters:{...(value.parameters||{})}}),[error,setError]=useState('');const category=categories.find(c=>c.id===Number(form.categoryId));
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{const payload={...form,categoryId:form.categoryId?Number(form.categoryId):null,parameters:form.parameters||{},offers:undefined,category:undefined};await api(`/products${form.id?`/${form.id}`:''}`,{method:form.id?'PUT':'POST',body:JSON.stringify(payload)});onSaved()}catch(err){setError((err as Error).message)}}
 return <Modal title={form.id?'Artikel bearbeiten':'Artikel anlegen'} wide onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Abbrechen</Button><Button variant="primary" type="submit" form="product-form">Speichern</Button></>}><form id="product-form" onSubmit={submit}>{error&&<div className="notice">{error}</div>}<div className="form-grid"><Field label="SKU"><input required value={form.sku||''} onChange={e=>setForm(f=>({...f,sku:e.target.value}))}/></Field><Field label="Name"><input required value={form.name||''} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></Field><Field label="Kategorie"><select value={form.categoryId||''} onChange={e=>setForm(f=>({...f,categoryId:Number(e.target.value),parameters:{}}))}><option value="">Ohne Kategorie</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Einheit"><input value={form.unit||''} onChange={e=>setForm(f=>({...f,unit:e.target.value}))}/></Field><Field label="Hersteller"><input value={form.manufacturer||''} onChange={e=>setForm(f=>({...f,manufacturer:e.target.value}))}/></Field><Field label="Modell"><input value={form.model||''} onChange={e=>setForm(f=>({...f,model:e.target.value}))}/></Field><Field label="Beschreibung" full><textarea value={form.description||''} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></Field>{category?.parameterSchema?.map(def=><Field label={`${def.label}${def.unit?` (${def.unit})`:''}`} key={def.key}>{def.type==='select'?<select value={String(form.parameters?.[def.key]??'')} onChange={e=>setForm(f=>({...f,parameters:{...f.parameters,[def.key]:e.target.value}}))}><option value="">Bitte wählen</option>{def.options?.map(o=><option key={o}>{o}</option>)}</select>:def.type==='boolean'?<select value={String(form.parameters?.[def.key]??'')} onChange={e=>setForm(f=>({...f,parameters:{...f.parameters,[def.key]:e.target.value==='true'}}))}><option value="">Bitte wählen</option><option value="true">Ja</option><option value="false">Nein</option></select>:<input type={def.type==='number'?'number':'text'} value={String(form.parameters?.[def.key]??'')} onChange={e=>setForm(f=>({...f,parameters:{...f.parameters,[def.key]:def.type==='number'?Number(e.target.value):e.target.value}}))}/>}</Field>)}</div></form></Modal>
}

function OfferModal({product,suppliers,onClose,onSaved}:{product:Product;suppliers:Supplier[];onClose:()=>void;onSaved:()=>void}){const [form,setForm]=useState({...emptyOffer}),[price,setPrice]=useState(''),[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await api(`/products/${product.id}/offers`,{method:'POST',body:JSON.stringify({...form,supplierId:Number(form.supplierId),priceCents:Math.round(Number(price.replace(',','.'))*100)})});onSaved()}catch(err){setError((err as Error).message)}};return <Modal title={`Bezugsquelle · ${product.name}`} onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Abbrechen</Button><Button variant="primary" type="submit" form="offer-form">Speichern</Button></>}><form id="offer-form" onSubmit={submit}>{error&&<div className="notice">{error}</div>}<div className="form-grid"><Field label="Lieferant"><select required value={form.supplierId} onChange={e=>setForm(f=>({...f,supplierId:Number(e.target.value)}))}><option value="0">Bitte wählen</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.preferred?'★ ':''}{s.name}</option>)}</select></Field><Field label="Preis EUR"><input required type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></Field><Field label="Lieferanten-SKU"><input value={form.supplierSku} onChange={e=>setForm(f=>({...f,supplierSku:e.target.value}))}/></Field><Field label="Lieferzeit (Tage)"><input type="number" min="0" value={form.leadDays} onChange={e=>setForm(f=>({...f,leadDays:Number(e.target.value)}))}/></Field><Field label="Mindestmenge"><input type="number" min="0.01" step="0.01" value={form.minimumQuantity} onChange={e=>setForm(f=>({...f,minimumQuantity:Number(e.target.value)}))}/></Field><Field label="Packgröße"><input type="number" min="0.01" step="0.01" value={form.packSize} onChange={e=>setForm(f=>({...f,packSize:Number(e.target.value)}))}/></Field><Field label="Einkaufslink" full><input type="url" value={form.purchaseUrl} onChange={e=>setForm(f=>({...f,purchaseUrl:e.target.value}))} placeholder="https://…"/></Field></div></form></Modal>}

function AlertModal({product,onClose,onSaved}:{product:Product;onClose:()=>void;onSaved:()=>void}){const [price,setPrice]=useState(''),[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await api('/alerts',{method:'POST',body:JSON.stringify({productId:product.id,targetPriceCents:Math.round(Number(price.replace(',','.'))*100),currency:'EUR'})});onSaved()}catch(err){setError((err as Error).message)}};return <Modal title={`Tiefpreis-Alarm · ${product.name}`} onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Abbrechen</Button><Button variant="primary" type="submit" form="alert-form">Alarm anlegen</Button></>}><form id="alert-form" onSubmit={submit}>{error&&<div className="notice">{error}</div>}<Field label="Zielpreis EUR"><input required autoFocus type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></Field><p style={{color:'var(--text-muted)',fontSize:'.76rem'}}>Der Alarm löst sofort aus, wenn ein vorhandenes oder später gepflegtes Angebot diesen Preis erreicht oder unterschreitet.</p></form></Modal>}

function CategoryModal({categories,onClose,onSaved}:{categories:Category[];onClose:()=>void;onSaved:()=>void}){
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[parameters,setParameters]=useState<ParameterDraft[]>([]),[error,setError]=useState('')
 const update=(index:number,patch:Partial<ParameterDraft>)=>setParameters(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row))
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{await api('/categories',{method:'POST',body:JSON.stringify({name,description,parameterSchema:buildParameterSchema(parameters)})});onSaved()}catch(err){setError((err as Error).message)}}
 return <Modal title="Kategorien & Parameter" wide onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Schließen</Button><Button variant="primary" type="submit" form="category-form">Kategorie anlegen</Button></>}>
  <div className="param-chips">{categories.map(c=><Badge key={c.id}>{c.name} · {c.parameterSchema?.length||0} Parameter</Badge>)}</div>
  <form id="category-form" onSubmit={submit}>{error&&<div className="notice">{error}</div>}<div className="form-grid"><Field label="Name"><input required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Beschreibung"><input value={description} onChange={e=>setDescription(e.target.value)}/></Field></div>
   <div className="parameter-heading"><div><h4>Suchparameter</h4><p>Diese Felder erscheinen später automatisch bei Artikeln und in der Parametersuche.</p></div><Button variant="ghost" type="button" onClick={()=>setParameters(rows=>[...rows,emptyParameter()])}><Plus size={15}/> Parameter hinzufügen</Button></div>
   {parameters.length===0?<div className="parameter-empty">Noch keine Parameter. Du kannst die Kategorie auch ohne Parameter anlegen.</div>:<div className="parameter-list">{parameters.map((parameter,index)=><div className={`parameter-editor${parameter.type==='select'?' has-options':''}`} key={index}>
    <Field label="Parametername"><input required value={parameter.label} onChange={e=>update(index,{label:e.target.value})} placeholder="z. B. Leistung"/></Field>
    <Field label="Feldtyp"><select value={parameter.type} onChange={e=>update(index,{type:e.target.value as ParameterDraft['type']})}><option value="text">Text</option><option value="number">Zahl</option><option value="select">Auswahlliste</option><option value="boolean">Ja / Nein</option></select></Field>
    <Field label="Einheit (optional)"><input value={parameter.unit} onChange={e=>update(index,{unit:e.target.value})} placeholder="z. B. W, mm, kg"/></Field>
    {parameter.type==='select'&&<Field label="Auswahlmöglichkeiten"><input required value={parameter.options} onChange={e=>update(index,{options:e.target.value})} placeholder="Schwarz, Weiß, Rot"/></Field>}
    <Button className="icon parameter-remove" variant="danger" type="button" onClick={()=>setParameters(rows=>rows.filter((_,i)=>i!==index))} title="Parameter entfernen"><Trash2 size={16}/></Button>
   </div>)}</div>}
  </form>
 </Modal>
}
