import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowDown, ArrowUp, ArrowUpDown, BellPlus, ExternalLink, Filter, Link2, Pencil, Plus, Search, Star, Trash2, WandSparkles } from 'lucide-react'
import { api, euro } from '../lib/api'
import type { Category, Offer, Product, ProductImportPreview, Supplier } from '../lib/types'
import { buildParameterSchema, editParameters, emptyParameter, mapImportedParameters, type ParameterDraft } from '../lib/parameters'
import { Badge, Button, Empty, Field, Modal } from '../components/ui'
import { useApp } from '../App'

const emptyProduct:Partial<Product>={sku:'',name:'',description:'',unit:'Stk.',manufacturer:'',model:'',parameters:{},attributes:{},active:true,reorderPoint:0,targetStock:0}
const emptyOffer:Partial<Offer>={supplierId:0,supplierSku:'',priceCents:0,currency:'EUR',minimumQuantity:1,packSize:1,leadDays:0,purchaseUrl:'',active:true}
export type SortKey='sku'|'name'|'manufacturer'|'offers'|'price'
export type SortState={key:SortKey;direction:'asc'|'desc'}
const collator=new Intl.Collator('de',{numeric:true,sensitivity:'base'})
export const sortProducts=(products:Product[],sort:SortState)=>[...products].sort((a,b)=>{let comparison=0;if(sort.key==='offers'){comparison=(a.offers?.length||0)-(b.offers?.length||0)}else if(sort.key==='price'){const aPrice=a.offers?.length?Math.min(...a.offers.map(o=>o.priceCents)):null,bPrice=b.offers?.length?Math.min(...b.offers.map(o=>o.priceCents)):null;if(aPrice==null||bPrice==null)return aPrice==null&&bPrice==null?collator.compare(a.name,b.name):aPrice==null?1:-1;comparison=aPrice-bPrice}else{const aValue=sort.key==='sku'?a.sku:sort.key==='manufacturer'?a.manufacturer:a.name,bValue=sort.key==='sku'?b.sku:sort.key==='manufacturer'?b.manufacturer:b.name;if(!aValue||!bValue)return !aValue&&!bValue?collator.compare(a.name,b.name):!aValue?1:-1;comparison=collator.compare(aValue,bValue)}return (sort.direction==='asc'?comparison:-comparison)||collator.compare(a.name,b.name)})

export default function CatalogPage(){
 const {user,refreshKey,refresh,notify}=useApp(),[products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[q,setQ]=useState(''),[categoryId,setCategoryId]=useState(''),[preferred,setPreferred]=useState(false),[params,setParams]=useState<Record<string,string>>({}),[showFilters,setShowFilters]=useState(false),[edit,setEdit]=useState<Partial<Product>|null>(null),[detail,setDetail]=useState<Product|null>(null),[offerFor,setOfferFor]=useState<Product|null>(null),[alertFor,setAlertFor]=useState<Product|null>(null),[categoryModal,setCategoryModal]=useState(false),[importModal,setImportModal]=useState(false),[sort,setSort]=useState<SortState>({key:'name',direction:'asc'})
 const selectedCategory=categories.find(c=>String(c.id)===categoryId)
 const sortedProducts=useMemo(()=>sortProducts(products,sort),[products,sort])
 const changeSort=(key:SortKey)=>setSort(current=>({key,direction:current.key===key&&current.direction==='asc'?'desc':'asc'}))
 const load=()=>{const query=new URLSearchParams();if(q)query.set('q',q);if(categoryId)query.set('categoryId',categoryId);if(preferred)query.set('preferred','true');Object.entries(params).filter(([,v])=>v!=='').forEach(([k,v])=>query.append('param',`${k}:${v}`));api<Product[]>(`/products?${query}`).then(setProducts)}
 useEffect(()=>{Promise.all([api<Category[]>('/categories'),api<Supplier[]>('/suppliers?active=true')]).then(([c,s])=>{setCategories(c);setSuppliers(s)});load()},[refreshKey])
 useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[q,categoryId,preferred,params])
 const openDetail=async(id:number)=>setDetail(await api<Product>(`/products/${id}`))
 const remove=async(id:number)=>{if(!confirm('Artikel wirklich löschen?'))return;await api(`/products/${id}`,{method:'DELETE'});notify('Artikel gelöscht');refresh()}
 return <div className="content"><div className="page-header"><div><h2>Beschaffungskatalog</h2><p>Technische Parameter durchsuchen, Bezugsquellen vergleichen und direkt einkaufen.</p></div>{user.isAdmin&&<div className="catalog-actions"><Button variant="ghost" onClick={()=>setImportModal(true)}><Link2 size={16}/> Aus Link</Button><Button variant="ghost" onClick={()=>setCategoryModal(true)}>Kategorien</Button><Button variant="primary" onClick={()=>setEdit({...emptyProduct})}><Plus size={17}/> Artikel</Button></div>}</div>
 <div className="toolbar"><div className="search suite-search-field"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Artikel, Marke, Modell, SKU, Lieferant oder Parameter …"/></div><select value={categoryId} onChange={e=>{setCategoryId(e.target.value);setParams({})}}><option value="">Alle Kategorien</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><label className="check"><input type="checkbox" checked={preferred} onChange={e=>setPreferred(e.target.checked)}/><Star size={15}/> Preferred</label><Button variant="ghost" onClick={()=>setShowFilters(!showFilters)}><Filter size={16}/> Parameter</Button></div>
 {showFilters&&<div className="filter-grid">{selectedCategory?.parameterSchema?.length?selectedCategory.parameterSchema.map(def=><Field key={def.key} label={`${def.label}${def.unit?` (${def.unit})`:''}`}>{def.type==='select'?<select value={params[def.key]||''} onChange={e=>setParams(p=>({...p,[def.key]:e.target.value}))}><option value="">Alle</option>{def.options?.map(o=><option key={o}>{o}</option>)}</select>:def.type==='boolean'?<select value={params[def.key]||''} onChange={e=>setParams(p=>({...p,[def.key]:e.target.value}))}><option value="">Alle</option><option value="true">Ja</option><option value="false">Nein</option></select>:<input type={def.type==='number'?'number':'text'} value={params[def.key]||''} onChange={e=>setParams(p=>({...p,[def.key]:e.target.value}))}/>}</Field>):<div style={{color:'var(--text-muted)',fontSize:'.78rem'}}>Wähle eine Kategorie mit Parameterschema.</div>}</div>}
 {products.length?<div className="table-wrap catalog-table"><table><thead><tr><SortHeader label="SKU" column="sku" sort={sort} onSort={changeSort}/><SortHeader label="Artikel" column="name" sort={sort} onSort={changeSort}/><SortHeader label="Hersteller" column="manufacturer" sort={sort} onSort={changeSort}/><th>Technische Parameter</th><SortHeader label="Bezugsquellen" column="offers" sort={sort} onSort={changeSort}/><SortHeader label="Bestpreis" column="price" sort={sort} onSort={changeSort}/><th></th></tr></thead><tbody>{sortedProducts.map(product=>{const offers=[...(product.offers||[])].sort((a,b)=>a.priceCents-b.priceCents),best=offers[0];return <tr key={product.id}><td><span className="catalog-sku">{product.sku}</span></td><td><div className="cell-title">{product.name}</div><div className="cell-sub">{product.category?.name||product.description||'Ohne Kategorie'}</div></td><td>{product.manufacturer||'–'}<div className="cell-sub">{product.model||'–'}</div></td><td><div className="param-chips catalog-params">{Object.entries(product.parameters||{}).slice(0,4).map(([k,v])=><span className="param-chip" key={k}>{k}: {String(v)}</span>)}{Object.keys(product.parameters||{}).length===0&&<span className="cell-sub">Keine Parameter</span>}</div></td><td><span className="source-count">{offers.length}</span> Bezugsquelle{offers.length===1?'':'n'}{best?.supplier?.preferred&&<div className="cell-sub preferred-source"><Star size={11}/> Preferred Supplier</div>}</td><td><span className="table-price">{best?euro(best.priceCents):'Kein Preis'}</span><div className="cell-sub">{best?.supplier?.name||'–'}</div></td><td><div className="row-actions"><Button className="icon" variant="ghost" onClick={()=>setAlertFor(product)} title="Tiefpreis-Alarm" aria-label={`Tiefpreis-Alarm für ${product.name}`}><BellPlus size={16}/></Button>{user.isAdmin&&<Button className="icon" variant="ghost" onClick={()=>setOfferFor(product)} title="Angebot hinzufügen" aria-label={`Angebot für ${product.name} hinzufügen`}><Plus size={16}/></Button>}<Button variant="primary" onClick={()=>openDetail(product.id)}>Details</Button></div></td></tr>})}</tbody></table></div>:<Empty>Keine Artikel passen zu den gewählten Parametern.</Empty>}
 {edit&&<ProductModal value={edit} categories={categories} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);notify('Artikel gespeichert');refresh()}}/>}
 {detail&&<Modal title={detail.name} wide onClose={()=>setDetail(null)} footer={<><Button variant="ghost" onClick={()=>setDetail(null)}>Schließen</Button>{user.isAdmin&&<><Button variant="danger" onClick={()=>{remove(detail.id);setDetail(null)}}><Trash2 size={16}/> Löschen</Button><Button variant="primary" onClick={()=>{setEdit(detail);setDetail(null)}}><Pencil size={16}/> Bearbeiten</Button></>}</>}><div className="form-grid"><Field label="SKU"><div className="cell-title">{detail.sku}</div></Field><Field label="Kategorie"><div>{detail.category?.name||'–'}</div></Field><Field label="Beschreibung" full><div>{detail.description||'–'}</div></Field></div>{Object.keys(detail.attributes||{}).length>0&&<><h4>Kategorieunabhängige Attribute</h4><div className="scraped-attributes">{Object.entries(detail.attributes).map(([key,value])=><span key={key}><strong>{key}</strong>{value}</span>)}</div></>}<h4>Bezugsquellen</h4><div className="table-wrap"><table><thead><tr><th>Lieferant</th><th>Preis</th><th>Lieferzeit</th><th></th></tr></thead><tbody>{detail.offers?.map(o=><tr key={o.id}><td><span className="cell-title">{o.supplier?.name}</span>{o.supplier?.preferred&&<span> ★</span>}</td><td>{euro(o.priceCents)}</td><td>{o.leadDays} Tage</td><td>{o.purchaseUrl&&<a className="btn primary" href={o.purchaseUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Einkaufen</a>}</td></tr>)}</tbody></table></div></Modal>}
 {offerFor&&<OfferModal product={offerFor} suppliers={suppliers} onClose={()=>setOfferFor(null)} onSaved={()=>{setOfferFor(null);notify('Bezugsquelle gespeichert');refresh()}}/>}
 {alertFor&&<AlertModal product={alertFor} onClose={()=>setAlertFor(null)} onSaved={()=>{setAlertFor(null);notify('Tiefpreis-Alarm angelegt');refresh()}}/>}
 {categoryModal&&<CategoryModal categories={categories} onClose={()=>setCategoryModal(false)} onSaved={message=>{setCategoryModal(false);notify(message);refresh()}}/>}
 {importModal&&<ImportProductModal categories={categories} suppliers={suppliers} onClose={()=>setImportModal(false)} onSaved={()=>{setImportModal(false);notify('Artikel aus Produktlink übernommen');refresh()}}/>}
 </div>
}

function SortHeader({label,column,sort,onSort}:{label:string;column:SortKey;sort:SortState;onSort:(key:SortKey)=>void}){const active=sort.key===column,Icon=active?(sort.direction==='asc'?ArrowUp:ArrowDown):ArrowUpDown;return <th className="sortable" aria-sort={active?(sort.direction==='asc'?'ascending':'descending'):'none'}><button className="sort-button" type="button" onClick={()=>onSort(column)}>{label}<Icon size={13} aria-hidden="true"/></button></th>}

function ImportProductModal({categories,suppliers,onClose,onSaved}:{categories:Category[];suppliers:Supplier[];onClose:()=>void;onSaved:()=>void}){
 const [url,setURL]=useState(''),[preview,setPreview]=useState<ProductImportPreview|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
 const [sku,setSKU]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[manufacturer,setManufacturer]=useState(''),[model,setModel]=useState(''),[unit,setUnit]=useState('Stk.'),[categoryId,setCategoryId]=useState(''),[supplierId,setSupplierId]=useState(''),[price,setPrice]=useState(''),[currency,setCurrency]=useState('EUR')
 const [parameterValues,setParameterValues]=useState<Product['parameters']>({})
 const selectedCategory=categories.find(category=>String(category.id)===categoryId)
 const matchingSupplier=(purchaseURL:string)=>{try{const host=new URL(purchaseURL).hostname.replace(/^www\./,'');return suppliers.find(s=>{try{return new URL(s.website).hostname.replace(/^www\./,'')===host}catch{return false}})}catch{return undefined}}
 const selectCategory=(value:string)=>{setCategoryId(value);const category=categories.find(item=>String(item.id)===value);setParameterValues(preview?mapImportedParameters(category?.parameterSchema,preview.attributes):{})}
 const inspect=async()=>{setLoading(true);setError('');try{const result=await api<ProductImportPreview>('/products/import-preview',{method:'POST',body:JSON.stringify({url})});setPreview(result);setSKU(result.sku||result.model||'');setName(result.name);setDescription(result.description);setManufacturer(result.manufacturer);setModel(result.model);setPrice(result.priceCents?(result.priceCents/100).toFixed(2):'');setCurrency(result.currency||'EUR');setParameterValues(mapImportedParameters(selectedCategory?.parameterSchema,result.attributes));const supplier=matchingSupplier(result.purchaseUrl);setSupplierId(supplier?String(supplier.id):'')}catch(err){setError((err as Error).message);setPreview(null);setParameterValues({})}finally{setLoading(false)}}
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!preview){setError('Bitte zuerst den Produktlink analysieren.');return}const parsedPrice=Math.round(Number(price.replace(',','.'))*100);if(parsedPrice>0&&!supplierId){setError('Bitte einen Lieferanten für den gefundenen Preis wählen.');return}setLoading(true);setError('');let created:Product|undefined;try{created=await api<Product>('/products',{method:'POST',body:JSON.stringify({sku,name,description,manufacturer,model,unit,categoryId:categoryId?Number(categoryId):null,parameters:parameterValues,attributes:preview.attributes,active:true,reorderPoint:0,targetStock:0})});if(supplierId&&parsedPrice>0){await api(`/products/${created.id}/offers`,{method:'POST',body:JSON.stringify({supplierId:Number(supplierId),priceCents:parsedPrice,currency,minimumQuantity:1,packSize:1,leadDays:0,purchaseUrl:preview.purchaseUrl,active:true})})}onSaved()}catch(err){if(created){await api(`/products/${created.id}`,{method:'DELETE'}).catch(()=>undefined)}setError((err as Error).message)}finally{setLoading(false)}}
 return <Modal title="Artikel aus Produktlink" wide onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Abbrechen</Button><Button variant="primary" type="submit" form="import-product-form" disabled={loading||!preview}><WandSparkles size={16}/> Artikel übernehmen</Button></>}>
  <form id="import-product-form" onSubmit={submit}>{error&&<div className="notice">{error}</div>}<div className="link-import"><input type="url" required value={url} onChange={e=>setURL(e.target.value)} placeholder="https://shop.example/produkt"/><Button variant="ghost" type="button" disabled={loading||!url} onClick={inspect}><Search size={16}/>{loading?'Wird analysiert …':'Link analysieren'}</Button></div>
  <p className="import-hint">ProcurementCore liest JSON-LD, schema.org-Microdata und OpenGraph. Eigene Adapter unterstützen unter anderem Adam Hall, LTT, Huss, Thomann, Steinigke, Eurobox- und Casebau-Shops. Bei konfiguriertem Adam-Hall-Konto wird zusätzlich der Kundenpreis geladen. Alle Werte können vor dem Speichern geprüft und geändert werden.</p>
  {preview&&<><div className="import-source"><Badge tone="accent"><WandSparkles size={12}/>{preview.source}</Badge>{Object.keys(preview.attributes).length>0&&<span>{Object.keys(preview.attributes).length} technische Angaben erkannt</span>}</div><div className="form-grid">
   <Field label="SKU"><input required value={sku} onChange={e=>setSKU(e.target.value)} placeholder="Interne oder Hersteller-SKU"/></Field><Field label="Artikelname"><input required value={name} onChange={e=>setName(e.target.value)}/></Field>
   <Field label="Kategorie"><select value={categoryId} onChange={e=>selectCategory(e.target.value)}><option value="">Ohne Kategorie</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Einheit"><input required value={unit} onChange={e=>setUnit(e.target.value)}/></Field>
   <Field label="Hersteller"><input value={manufacturer} onChange={e=>setManufacturer(e.target.value)}/></Field><Field label="Modell"><input value={model} onChange={e=>setModel(e.target.value)}/></Field>
   <Field label="Beschreibung" full><textarea value={description} onChange={e=>setDescription(e.target.value)}/></Field><Field label="Lieferant für Bezugsquelle"><select value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Kein Angebot anlegen</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.preferred?'★ ':''}{s.name}</option>)}</select></Field>
   <Field label="Gefundener Preis"><div className="price-input"><input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/><input className="currency" maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></div></Field>
  </div>{selectedCategory?.parameterSchema?.length?<div className="import-parameters"><h4>Kategorieparameter</h4><p>Erkannte Werte sind vorausgefüllt und können vor dem Import angepasst werden.</p><div className="form-grid">{selectedCategory.parameterSchema.map(def=><Field label={`${def.label}${def.unit?` (${def.unit})`:''}`} key={def.key}>{def.type==='select'?<select value={String(parameterValues[def.key]??'')} onChange={e=>setParameterValues(values=>({...values,[def.key]:e.target.value}))}><option value="">Bitte wählen</option>{def.options?.map(option=><option key={option}>{option}</option>)}</select>:def.type==='boolean'?<select value={String(parameterValues[def.key]??'')} onChange={e=>setParameterValues(values=>({...values,[def.key]:e.target.value===''?'':e.target.value==='true'}))}><option value="">Bitte wählen</option><option value="true">Ja</option><option value="false">Nein</option></select>:<input type={def.type==='number'?'number':'text'} value={String(parameterValues[def.key]??'')} onChange={e=>setParameterValues(values=>({...values,[def.key]:def.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value}))}/>}</Field>)}</div></div>:null}{Object.keys(preview.attributes).length>0&&<div className="scraped-attributes">{Object.entries(preview.attributes).map(([key,value])=><span key={key}><strong>{key}</strong>{value}</span>)}</div>}</>}
  </form>
 </Modal>
}

function ProductModal({value,categories,onClose,onSaved}:{value:Partial<Product>;categories:Category[];onClose:()=>void;onSaved:()=>void}){
 const [form,setForm]=useState<Partial<Product>>({...value,parameters:{...(value.parameters||{})},attributes:{...(value.attributes||{})}}),[error,setError]=useState('');const category=categories.find(c=>c.id===Number(form.categoryId));
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{const payload={...form,categoryId:form.categoryId?Number(form.categoryId):null,parameters:form.parameters||{},attributes:form.attributes||{},offers:undefined,category:undefined};await api(`/products${form.id?`/${form.id}`:''}`,{method:form.id?'PUT':'POST',body:JSON.stringify(payload)});onSaved()}catch(err){setError((err as Error).message)}}
 return <Modal title={form.id?'Artikel bearbeiten':'Artikel anlegen'} wide onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Abbrechen</Button><Button variant="primary" type="submit" form="product-form">Speichern</Button></>}>
  <form id="product-form" onSubmit={submit}>{error&&<div className="notice">{error}</div>}<div className="form-grid">
   <Field label="SKU"><input required value={form.sku||''} onChange={e=>setForm(f=>({...f,sku:e.target.value}))}/></Field><Field label="Name"><input required value={form.name||''} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></Field>
   <Field label="Kategorie"><select value={form.categoryId||''} onChange={e=>setForm(f=>({...f,categoryId:e.target.value?Number(e.target.value):undefined,parameters:{}}))}><option value="">Ohne Kategorie</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Einheit"><input value={form.unit||''} onChange={e=>setForm(f=>({...f,unit:e.target.value}))}/></Field>
   <Field label="Hersteller"><input value={form.manufacturer||''} onChange={e=>setForm(f=>({...f,manufacturer:e.target.value}))}/></Field><Field label="Modell"><input value={form.model||''} onChange={e=>setForm(f=>({...f,model:e.target.value}))}/></Field><Field label="Beschreibung" full><textarea value={form.description||''} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></Field>
   {category?.parameterSchema?.map(def=><Field label={`${def.label}${def.unit?` (${def.unit})`:''}`} key={def.key}>{def.type==='select'?<select value={String(form.parameters?.[def.key]??'')} onChange={e=>setForm(f=>({...f,parameters:{...f.parameters,[def.key]:e.target.value}}))}><option value="">Bitte wählen</option>{def.options?.map(o=><option key={o}>{o}</option>)}</select>:def.type==='boolean'?<select value={String(form.parameters?.[def.key]??'')} onChange={e=>setForm(f=>({...f,parameters:{...f.parameters,[def.key]:e.target.value==='true'}}))}><option value="">Bitte wählen</option><option value="true">Ja</option><option value="false">Nein</option></select>:<input type={def.type==='number'?'number':'text'} value={String(form.parameters?.[def.key]??'')} onChange={e=>setForm(f=>({...f,parameters:{...f.parameters,[def.key]:def.type==='number'?Number(e.target.value):e.target.value}}))}/>}</Field>)}
  </div>{Object.keys(form.attributes||{}).length>0&&<div className="import-parameters"><h4>Kategorieunabhängige Attribute</h4><p>Diese importierten Angaben bleiben auch ohne Kategorie erhalten und sind durchsuchbar.</p><div className="form-grid">{Object.entries(form.attributes||{}).map(([key,value])=><Field label={key} key={key}><input value={value} onChange={e=>setForm(f=>({...f,attributes:{...f.attributes,[key]:e.target.value}}))}/></Field>)}</div></div>}
  </form>
 </Modal>
}

function OfferModal({product,suppliers,onClose,onSaved}:{product:Product;suppliers:Supplier[];onClose:()=>void;onSaved:()=>void}){const [form,setForm]=useState({...emptyOffer}),[price,setPrice]=useState(''),[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await api(`/products/${product.id}/offers`,{method:'POST',body:JSON.stringify({...form,supplierId:Number(form.supplierId),priceCents:Math.round(Number(price.replace(',','.'))*100)})});onSaved()}catch(err){setError((err as Error).message)}};return <Modal title={`Bezugsquelle · ${product.name}`} onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Abbrechen</Button><Button variant="primary" type="submit" form="offer-form">Speichern</Button></>}><form id="offer-form" onSubmit={submit}>{error&&<div className="notice">{error}</div>}<div className="form-grid"><Field label="Lieferant"><select required value={form.supplierId} onChange={e=>setForm(f=>({...f,supplierId:Number(e.target.value)}))}><option value="0">Bitte wählen</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.preferred?'★ ':''}{s.name}</option>)}</select></Field><Field label="Preis EUR"><input required type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></Field><Field label="Lieferanten-SKU"><input value={form.supplierSku} onChange={e=>setForm(f=>({...f,supplierSku:e.target.value}))}/></Field><Field label="Lieferzeit (Tage)"><input type="number" min="0" value={form.leadDays} onChange={e=>setForm(f=>({...f,leadDays:Number(e.target.value)}))}/></Field><Field label="Mindestmenge"><input type="number" min="0.01" step="0.01" value={form.minimumQuantity} onChange={e=>setForm(f=>({...f,minimumQuantity:Number(e.target.value)}))}/></Field><Field label="Packgröße"><input type="number" min="0.01" step="0.01" value={form.packSize} onChange={e=>setForm(f=>({...f,packSize:Number(e.target.value)}))}/></Field><Field label="Einkaufslink" full><input type="url" value={form.purchaseUrl} onChange={e=>setForm(f=>({...f,purchaseUrl:e.target.value}))} placeholder="https://…"/></Field></div></form></Modal>}

function AlertModal({product,onClose,onSaved}:{product:Product;onClose:()=>void;onSaved:()=>void}){const [price,setPrice]=useState(''),[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await api('/alerts',{method:'POST',body:JSON.stringify({productId:product.id,targetPriceCents:Math.round(Number(price.replace(',','.'))*100),currency:'EUR'})});onSaved()}catch(err){setError((err as Error).message)}};return <Modal title={`Tiefpreis-Alarm · ${product.name}`} onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Abbrechen</Button><Button variant="primary" type="submit" form="alert-form">Alarm anlegen</Button></>}><form id="alert-form" onSubmit={submit}>{error&&<div className="notice">{error}</div>}<Field label="Zielpreis EUR"><input required autoFocus type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></Field><p style={{color:'var(--text-muted)',fontSize:'.76rem'}}>Der Alarm löst sofort aus, wenn ein vorhandenes oder später gepflegtes Angebot diesen Preis erreicht oder unterschreitet.</p></form></Modal>}

function CategoryModal({categories,onClose,onSaved}:{categories:Category[];onClose:()=>void;onSaved:(message:string)=>void}){
 const [editing,setEditing]=useState<Category|null>(null),[name,setName]=useState(''),[description,setDescription]=useState(''),[parameters,setParameters]=useState<ParameterDraft[]>([]),[error,setError]=useState('')
 const update=(index:number,patch:Partial<ParameterDraft>)=>setParameters(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row))
 const reset=()=>{setEditing(null);setName('');setDescription('');setParameters([]);setError('')}
 const startEdit=(category:Category)=>{setEditing(category);setName(category.name);setDescription(category.description||'');setParameters(editParameters(category.parameterSchema));setError('')}
 const remove=async(category:Category)=>{if(!confirm(`Kategorie „${category.name}“ wirklich löschen?`))return;setError('');try{await api(`/categories/${category.id}`,{method:'DELETE'});onSaved('Kategorie gelöscht')}catch(err){setError((err as Error).message)}}
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{await api(editing?`/categories/${editing.id}`:'/categories',{method:editing?'PUT':'POST',body:JSON.stringify({name,description,parameterSchema:buildParameterSchema(parameters)})});onSaved(editing?'Kategorie gespeichert':'Kategorie angelegt')}catch(err){setError((err as Error).message)}}
 return <Modal title="Kategorien & Parameter" wide onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Schließen</Button>{editing&&<Button variant="ghost" onClick={reset}>Neue Kategorie</Button>}<Button variant="primary" type="submit" form="category-form">{editing?'Änderungen speichern':'Kategorie anlegen'}</Button></>}>
  {categories.length?<div className="category-manager-list">{categories.map(category=><div className={`category-manager-row${editing?.id===category.id?' active':''}`} key={category.id}><div><strong>{category.name}</strong><span>{category.parameterSchema?.length||0} Parameter{category.description?` · ${category.description}`:''}</span></div><div className="row-actions"><Button className="icon" variant="ghost" type="button" onClick={()=>startEdit(category)} title="Kategorie bearbeiten"><Pencil size={15}/></Button><Button className="icon" variant="danger" type="button" onClick={()=>remove(category)} title="Kategorie löschen"><Trash2 size={15}/></Button></div></div>)}</div>:<div className="parameter-empty">Noch keine Kategorien vorhanden.</div>}
  <form id="category-form" onSubmit={submit}>{error&&<div className="notice">{error}</div>}<div className="form-grid"><Field label="Name"><input required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Beschreibung"><input value={description} onChange={e=>setDescription(e.target.value)}/></Field></div>
   <div className="parameter-heading"><div><h4>{editing?`Parameter für ${editing.name}`:'Suchparameter'}</h4><p>Diese Felder erscheinen später automatisch bei Artikeln und in der Parametersuche.</p></div><Button variant="ghost" type="button" onClick={()=>setParameters(rows=>[...rows,emptyParameter()])}><Plus size={15}/> Parameter hinzufügen</Button></div>
   {parameters.length===0?<div className="parameter-empty">Noch keine Parameter. Du kannst die Kategorie auch ohne Parameter anlegen.</div>:<div className="parameter-list">{parameters.map((parameter,index)=><div className={`parameter-editor${parameter.type==='select'?' has-options':''}`} key={index}>
    <Field label="Parametername"><input required value={parameter.label} onChange={e=>update(index,{label:e.target.value})} placeholder="z. B. Leistung"/></Field>
    <Field label="Feldtyp"><select value={parameter.type} onChange={e=>update(index,{type:e.target.value as ParameterDraft['type']})}><option value="text">Text</option><option value="number">Zahl</option><option value="select">Auswahlliste</option><option value="boolean">Ja / Nein</option></select></Field>
    <Field label="Einheit (optional)"><input value={parameter.unit} onChange={e=>update(index,{unit:e.target.value})} placeholder="z. B. W, mm, kg"/></Field>
    {parameter.type==='select'&&<Field label="Auswahlmöglichkeiten"><input required value={parameter.options} onChange={e=>update(index,{options:e.target.value})} placeholder="Schwarz, Weiß, Rot"/></Field>}
    <Button className="icon parameter-remove" variant="danger" type="button" onClick={()=>setParameters(rows=>rows.filter((_,i)=>i!==index))} title="Parameter entfernen"><Trash2 size={16}/></Button>
   </div>)}</div>}
  </form>
 </Modal>
}
