import { FormEvent, useEffect, useState } from 'react'
import { ExternalLink, Pencil, Plus, Search, Star, Trash2 } from 'lucide-react'
import { api } from '../lib/api'
import type { Supplier } from '../lib/types'
import { Badge, Button, Empty, Field, Modal } from '../components/ui'
import { useApp } from '../App'

const blank:Partial<Supplier>={name:'',code:'',website:'',contactName:'',email:'',phone:'',paymentTerms:'',defaultLeadDays:0,rating:0,preferred:false,active:true,riskLevel:'low',notes:''}
export default function SuppliersPage(){const {user,refreshKey,refresh,notify}=useApp(),[rows,setRows]=useState<Supplier[]>([]),[q,setQ]=useState(''),[preferred,setPreferred]=useState(false),[edit,setEdit]=useState<Partial<Supplier>|null>(null);useEffect(()=>{const timer=setTimeout(()=>{const p=new URLSearchParams();if(q)p.set('q',q);if(preferred)p.set('preferred','true');api<Supplier[]>(`/suppliers?${p}`).then(setRows)},180);return()=>clearTimeout(timer)},[q,preferred,refreshKey]);const remove=async(row:Supplier)=>{if(!confirm(`${row.name} wirklich löschen?`))return;try{await api(`/suppliers/${row.id}`,{method:'DELETE'});notify('Lieferant gelöscht');refresh()}catch(e){notify((e as Error).message)}};return <div className="content"><div className="page-header"><div><h2>Lieferanten</h2><p>Bezugsquellen, Konditionen, Risiko und Präferenz zentral pflegen.</p></div>{user.isAdmin&&<Button variant="primary" onClick={()=>setEdit({...blank})}><Plus size={17}/> Lieferant</Button>}</div><div className="toolbar"><div className="search suite-search-field"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Name, Code oder E-Mail …"/></div><label className="check"><input type="checkbox" checked={preferred} onChange={e=>setPreferred(e.target.checked)}/><Star size={15}/> Nur Preferred Supplier</label></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>Lieferant</th><th>Kontakt</th><th>Konditionen</th><th>Bewertung</th><th>Risiko</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><div className="cell-title">{row.preferred&&<span className="preferred-star">★ </span>}{row.name}</div><div className="cell-sub">{row.code}</div></td><td>{row.contactName||'–'}<div className="cell-sub">{row.email}</div></td><td>{row.paymentTerms||'–'}<div className="cell-sub">{row.defaultLeadDays} Tage Standardlieferzeit</div></td><td>{row.rating.toFixed(1)} / 5</td><td><Badge tone={row.riskLevel==='low'?'green':row.riskLevel==='medium'?'amber':'red'}>{row.riskLevel}</Badge></td><td><div className="row-actions">{row.website&&<a className="btn ghost icon" href={row.website} target="_blank" rel="noreferrer"><ExternalLink size={15}/></a>}{user.isAdmin&&<><Button className="icon" variant="ghost" onClick={()=>setEdit(row)}><Pencil size={15}/></Button><Button className="icon" variant="danger" onClick={()=>remove(row)}><Trash2 size={15}/></Button></>}</div></td></tr>)}</tbody></table></div>:<Empty>Noch keine Lieferanten vorhanden.</Empty>}{edit&&<SupplierModal value={edit} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);notify('Lieferant gespeichert');refresh()}}/>}</div>}

function SupplierModal({value,onClose,onSaved}:{value:Partial<Supplier>;onClose:()=>void;onSaved:()=>void}){const [form,setForm]=useState(value),[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await api(`/suppliers${form.id?`/${form.id}`:''}`,{method:form.id?'PUT':'POST',body:JSON.stringify(form)});onSaved()}catch(err){setError((err as Error).message)}};return <Modal title={form.id?'Lieferant bearbeiten':'Lieferant anlegen'} wide onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Abbrechen</Button><Button variant="primary" form="supplier-form" type="submit">Speichern</Button></>}><form id="supplier-form" onSubmit={submit}>{error&&<div className="notice">{error}</div>}<div className="form-grid"><Field label="Name"><input required value={form.name||''} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></Field><Field label="Code"><input required value={form.code||''} onChange={e=>setForm(f=>({...f,code:e.target.value}))}/></Field><Field label="Kontakt"><input value={form.contactName||''} onChange={e=>setForm(f=>({...f,contactName:e.target.value}))}/></Field><Field label="E-Mail"><input type="email" value={form.email||''} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/></Field><Field label="Telefon"><input value={form.phone||''} onChange={e=>setForm(f=>({...f,phone:e.target.value}))}/></Field><Field label="Website"><input type="url" value={form.website||''} onChange={e=>setForm(f=>({...f,website:e.target.value}))}/></Field><Field label="Zahlungsbedingungen"><input value={form.paymentTerms||''} onChange={e=>setForm(f=>({...f,paymentTerms:e.target.value}))}/></Field><Field label="Standardlieferzeit (Tage)"><input type="number" min="0" value={form.defaultLeadDays||0} onChange={e=>setForm(f=>({...f,defaultLeadDays:Number(e.target.value)}))}/></Field><Field label="Bewertung (0–5)"><input type="number" min="0" max="5" step="0.1" value={form.rating||0} onChange={e=>setForm(f=>({...f,rating:Number(e.target.value)}))}/></Field><Field label="Risiko"><select value={form.riskLevel} onChange={e=>setForm(f=>({...f,riskLevel:e.target.value as Supplier['riskLevel']}))}><option value="low">Niedrig</option><option value="medium">Mittel</option><option value="high">Hoch</option></select></Field><Field label="Notizen" full><textarea value={form.notes||''} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></Field><label className="check"><input type="checkbox" checked={form.preferred||false} onChange={e=>setForm(f=>({...f,preferred:e.target.checked}))}/><Star size={15}/> Preferred Supplier</label><label className="check"><input type="checkbox" checked={form.active??true} onChange={e=>setForm(f=>({...f,active:e.target.checked}))}/> Aktiv</label></div></form></Modal>}
